### ISSUE TITLE
[Ask] [Enhancement] 如何調高 ChatGPT 回應的字數

### ISSUE THREAD

**Issue by androchentw** [memochou1993/ai-assistant#1]
---

name: Feature request
about: Suggest an idea for this project
title: 如何調高 ChatGPT 回應的字數
labels: ask
assignees: @memochou1993

---

**Is your feature request related to a problem? Please describe.**
現在回應的字數似乎在 200 左右?
即便嘗試調整 [maxTokens](https://github.com/memochou1993/ai-assistant/commit/e167f1726ac7cad79e9538e21afe2a5b1c068eb0) 也沒什麼效果, 請問有什麼建議嗎?

**Additional context**
感謝 說明得很清楚 🥳

**Comment by memochou1993** [comment]
感謝回饋。

請問你指的是希望它回覆更多的文字給你嗎？如果是的話，是不是用「請詳細說明」或「請詳細解釋」詢問它看看。

如果是指說，已經調整程式設定，但是沒有起到反應，可能要看看應用程式有沒有重新部署成功。

**Comment by androchentw** [comment]
不知道是不是我斷詞的地方不對😂
我嘗試過直接指定回覆 500 字 這樣, 在網頁版 & 另一種指定 maxTokens 的串接方式時, 是可以取得比較完整的描述的 (稍後補連結)，所以才會好奇是不是這邊的實作參數要另外調整～ 我再試試看 謝謝🙏

**Comment by memochou1993** [comment]
@androchentw 

嗨！我後來有做以下更新：

1. 把 timeout 改成 60 秒
2. 把 Completion API 的參數抽出來做成環境變數

可以考慮用「Sync fork」按鈕來同步專案。

直接在本地專案測試也可以，不過要注意 OpenAI API 是有額度的唷～
